from __future__ import annotations

from dataclasses import dataclass
import os
from pathlib import Path
from typing import Any


def _to_relative_import(from_path: Path, to_path: Path) -> str:
    from_dir = from_path.parent.resolve()
    abs_to = to_path.resolve()
    rel = os.path.relpath(str(abs_to), str(from_dir)).replace("\\", "/")
    if rel.endswith(".py"):
        rel = rel[:-3]

    parts = rel.split("/")
    up = 0
    while up < len(parts) and parts[up] == "..":
        up += 1

    module_parts = [part for part in parts[up:] if part and part != "."]
    prefix = "." * (up + 1)
    if module_parts:
        return prefix + ".".join(module_parts)
    return prefix.rstrip(".") or "."


@dataclass(frozen=True, slots=True)
class GenerateClientOptions:
    datasources: dict[str, Any]
    pipes: dict[str, Any]
    output_path: str
    cwd: str
    datasource_source_files: dict[str, str] | None = None
    pipe_source_files: dict[str, str] | None = None


@dataclass(frozen=True, slots=True)
class GeneratedClient:
    content: str
    absolute_path: str


def generate_client_file(options: GenerateClientOptions | dict[str, Any]) -> GeneratedClient:
    normalized = options if isinstance(options, GenerateClientOptions) else GenerateClientOptions(**options)

    output = Path(normalized.output_path)
    absolute_path = output if output.is_absolute() else Path(normalized.cwd) / output

    datasource_names = list(normalized.datasources.keys())
    pipe_names = list(normalized.pipes.keys())

    imports: list[str] = ["from tinybird_sdk import Tinybird"]

    datasource_source_files = normalized.datasource_source_files or {}
    pipe_source_files = normalized.pipe_source_files or {}

    imports_by_file: dict[str, list[str]] = {}
    for name in datasource_names:
        src = datasource_source_files.get(name)
        if src:
            imports_by_file.setdefault(src, []).append(name)
    for name in pipe_names:
        src = pipe_source_files.get(name)
        if src:
            imports_by_file.setdefault(src, []).append(name)

    if imports_by_file:
        for source_file, names in sorted(imports_by_file.items()):
            source_path = Path(source_file)
            if not source_path.is_absolute():
                source_path = Path(normalized.cwd) / source_path
            rel = _to_relative_import(absolute_path, source_path)
            imports.append(f"from {rel} import {', '.join(sorted(set(names)))}")
    else:
        if datasource_names:
            imports.append(f"from .datasources import {', '.join(datasource_names)}")
        if pipe_names:
            imports.append(f"from .pipes import {', '.join(pipe_names)}")

    lines: list[str] = [
        "# Auto-generated by tinybird_sdk - DO NOT EDIT",
        "",
        *imports,
        "",
        "tinybird = Tinybird({",
        f"    'datasources': {{{', '.join(f'{name!r}: {name}' for name in datasource_names)}}},",
        f"    'pipes': {{{', '.join(f'{name!r}: {name}' for name in pipe_names)}}},",
        "})",
        "",
    ]

    return GeneratedClient(content="\n".join(lines), absolute_path=str(absolute_path))
