"""
Generated by tinybird migrate.
Review endpoint output schemas and defaults before production use.
"""

from tinybird_sdk import define_datasource, define_kafka_connection, define_pipe, engine, node, t

# Connections

broker = define_kafka_connection("broker", {
    'bootstrap_servers': "localhost:9092",
})

# Datasources

"""
Event stream
"""
events = define_datasource("events", {
    'description': "Event stream",
    'json_paths': False,
    'schema': {
        'id': t.int32(),
        'country': t.string(),
    },
    'engine': engine.merge_tree({'sorting_key': "id"}),
})

# Pipes

"""
Top events endpoint
"""
top_events = define_pipe("top_events", {
    'description': "Top events endpoint",
    'nodes': [
        node({
            'name': "endpoint",
            'sql': '''
SELECT id AS id, country AS country FROM events
''',
        }),
    ],
    'endpoint': True,
    'output': {
        'id': t.string(),
        'country': t.string(),
    },
})
